### ISSUE TITLE
Objectives : 

### ISSUE THREAD

**Issue by endyappel** [Yotlan/football-world-history#1]
Objectives : 
- Yotlan 1888/1889 - 1899/1900
- Endy 1900/1901 - 1929/1930
- Samuel 1930/1931 - 1959/1960
- Florian 1960/1961 - 1991/1992

**Comment by endyappel** [comment]
finished saison of 1900/1901-1929/1930. 
Need equipe

**Comment by endyappel** [comment]
perhabs pb of rename in saison like : United or  Utd

**Comment by endyappel** [comment]
- pb of qualification or relegation in saison/1960-1961
- no attribut named GAv in wikipedia, solution proposed is : GAv = BM/BE , round to 2 significant digits ( from 1976-1977 to 1991-1992 in saison folder)
-  pb of double qualification , solution propososed is to use :  AND

**Comment by endyappel** [comment]
finished with saison of part of Florian

**Comment by endyappel** [comment]
finished equips complet

**Comment by Yotlan** [comment]
Already fix in previous commit
