### ISSUE TITLE
1900-1901 pb :

### ISSUE THREAD

**Issue by endyappel** [Yotlan/football-world-history#3]
equipe : 
line  : own goals present 
- Bury 1900 - 1901 , 
- Newcastle_Utd 1900-1901 : same pb
- Sheffield Utd 
- Preston North End
- Blackburn Rovers

rename of : 
- The wednesday to Sheffield Wednesday (today, name of csv)
- stoke to Stoke City (csv name is stoke)

**Comment by Yotlan** [comment]
Problem was almost fixed. Need to do the same for squad file

**Comment by Yotlan** [comment]
Already fix in previous commit
