### ISSUE TITLE
Name changeable of equips is possible !

### ISSUE THREAD

**Issue by endyappel** [Yotlan/football-world-history#5]
Small Heath => (1905) Birmingham => (1960) Birmingham_City
Stoke => (1963) Stoke_City
The_Wednesday => (1929-1930) Sheffield_Wednesday
Woolwich_Arsenal => (1919-1920) Arsenal
Leicester_City => Leicester_Fosse (possible)
Queens_Park_Rangers (real name is Queen's Park Rangers) confusion possible with other file

**Comment by Yotlan** [comment]
Already done in previous commit
